//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndritzHydro.Tuccos.Model {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Country", Namespace="http://schemas.datacontract.org/2004/07/AndritzHydro.Tuccos.Data")]
    [System.SerializableAttribute()]
    public partial class Country : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxNumber {
            get {
                return this.MaxNumberField;
            }
            set {
                if ((this.MaxNumberField.Equals(value) != true)) {
                    this.MaxNumberField = value;
                    this.RaisePropertyChanged("MaxNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberCount {
            get {
                return this.NumberCountField;
            }
            set {
                if ((this.NumberCountField.Equals(value) != true)) {
                    this.NumberCountField = value;
                    this.RaisePropertyChanged("NumberCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Project", Namespace="http://schemas.datacontract.org/2004/07/AndritzHydro.Tuccos.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AndritzHydro.Tuccos.Model.SubAssembly))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AndritzHydro.Tuccos.Model.Country[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AndritzHydro.Tuccos.Model.Country))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AndritzHydro.Tuccos.Model.Project[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AndritzHydro.Tuccos.Model.SubAssembly[]))]
    public partial class Project : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object[] SubassemblyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int _YearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object[] Subassembly {
            get {
                return this.SubassemblyField;
            }
            set {
                if ((object.ReferenceEquals(this.SubassemblyField, value) != true)) {
                    this.SubassemblyField = value;
                    this.RaisePropertyChanged("Subassembly");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _Id {
            get {
                return this._IdField;
            }
            set {
                if ((object.ReferenceEquals(this._IdField, value) != true)) {
                    this._IdField = value;
                    this.RaisePropertyChanged("_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _Name {
            get {
                return this._NameField;
            }
            set {
                if ((object.ReferenceEquals(this._NameField, value) != true)) {
                    this._NameField = value;
                    this.RaisePropertyChanged("_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _Year {
            get {
                return this._YearField;
            }
            set {
                if ((this._YearField.Equals(value) != true)) {
                    this._YearField = value;
                    this.RaisePropertyChanged("_Year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubAssembly", Namespace="http://schemas.datacontract.org/2004/07/AndritzHydro.Tuccos.Data")]
    [System.SerializableAttribute()]
    public partial class SubAssembly : AndritzHydro.Tuccos.Model.Project {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RngNrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SubAssemblyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubAssemblyNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RngNr {
            get {
                return this.RngNrField;
            }
            set {
                if ((this.RngNrField.Equals(value) != true)) {
                    this.RngNrField = value;
                    this.RaisePropertyChanged("RngNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SubAssemblyId {
            get {
                return this.SubAssemblyIdField;
            }
            set {
                if ((this.SubAssemblyIdField.Equals(value) != true)) {
                    this.SubAssemblyIdField = value;
                    this.RaisePropertyChanged("SubAssemblyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubAssemblyName {
            get {
                return this.SubAssemblyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SubAssemblyNameField, value) != true)) {
                    this.SubAssemblyNameField = value;
                    this.RaisePropertyChanged("SubAssemblyName");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Model.IProject")]
    public interface IProject {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProject/GetCountries", ReplyAction="http://tempuri.org/IProject/GetCountriesResponse")]
        AndritzHydro.Tuccos.Model.Country[] GetCountries(string language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProject/GetCountries", ReplyAction="http://tempuri.org/IProject/GetCountriesResponse")]
        System.Threading.Tasks.Task<AndritzHydro.Tuccos.Model.Country[]> GetCountriesAsync(string language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProject/GetProjectList", ReplyAction="http://tempuri.org/IProject/GetProjectListResponse")]
        AndritzHydro.Tuccos.Model.Project[] GetProjectList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProject/GetProjectList", ReplyAction="http://tempuri.org/IProject/GetProjectListResponse")]
        System.Threading.Tasks.Task<AndritzHydro.Tuccos.Model.Project[]> GetProjectListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProject/SaveProject", ReplyAction="http://tempuri.org/IProject/SaveProjectResponse")]
        void SaveProject(AndritzHydro.Tuccos.Model.Project project);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProject/SaveProject", ReplyAction="http://tempuri.org/IProject/SaveProjectResponse")]
        System.Threading.Tasks.Task SaveProjectAsync(AndritzHydro.Tuccos.Model.Project project);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProject/DeleteProject", ReplyAction="http://tempuri.org/IProject/DeleteProjectResponse")]
        void DeleteProject(AndritzHydro.Tuccos.Model.Project project);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProject/DeleteProject", ReplyAction="http://tempuri.org/IProject/DeleteProjectResponse")]
        System.Threading.Tasks.Task DeleteProjectAsync(AndritzHydro.Tuccos.Model.Project project);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProject/GetSubAssemblies", ReplyAction="http://tempuri.org/IProject/GetSubAssembliesResponse")]
        AndritzHydro.Tuccos.Model.SubAssembly[] GetSubAssemblies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProject/GetSubAssemblies", ReplyAction="http://tempuri.org/IProject/GetSubAssembliesResponse")]
        System.Threading.Tasks.Task<AndritzHydro.Tuccos.Model.SubAssembly[]> GetSubAssembliesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProjectChannel : AndritzHydro.Tuccos.Model.IProject, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProjectClient : System.ServiceModel.ClientBase<AndritzHydro.Tuccos.Model.IProject>, AndritzHydro.Tuccos.Model.IProject {
        
        public ProjectClient() {
        }
        
        public ProjectClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProjectClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AndritzHydro.Tuccos.Model.Country[] GetCountries(string language) {
            return base.Channel.GetCountries(language);
        }
        
        public System.Threading.Tasks.Task<AndritzHydro.Tuccos.Model.Country[]> GetCountriesAsync(string language) {
            return base.Channel.GetCountriesAsync(language);
        }
        
        public AndritzHydro.Tuccos.Model.Project[] GetProjectList() {
            return base.Channel.GetProjectList();
        }
        
        public System.Threading.Tasks.Task<AndritzHydro.Tuccos.Model.Project[]> GetProjectListAsync() {
            return base.Channel.GetProjectListAsync();
        }
        
        public void SaveProject(AndritzHydro.Tuccos.Model.Project project) {
            base.Channel.SaveProject(project);
        }
        
        public System.Threading.Tasks.Task SaveProjectAsync(AndritzHydro.Tuccos.Model.Project project) {
            return base.Channel.SaveProjectAsync(project);
        }
        
        public void DeleteProject(AndritzHydro.Tuccos.Model.Project project) {
            base.Channel.DeleteProject(project);
        }
        
        public System.Threading.Tasks.Task DeleteProjectAsync(AndritzHydro.Tuccos.Model.Project project) {
            return base.Channel.DeleteProjectAsync(project);
        }
        
        public AndritzHydro.Tuccos.Model.SubAssembly[] GetSubAssemblies() {
            return base.Channel.GetSubAssemblies();
        }
        
        public System.Threading.Tasks.Task<AndritzHydro.Tuccos.Model.SubAssembly[]> GetSubAssembliesAsync() {
            return base.Channel.GetSubAssembliesAsync();
        }
    }
}
