//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndritzHydro.Tuccos.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AndritzHydro.Tuccos.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TUCCOS - Turbine Calculation Service ähnelt.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bonus: ähnelt.
        /// </summary>
        public static string BonusNumber {
            get {
                return ResourceManager.GetString("BonusNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Busy ähnelt.
        /// </summary>
        public static string Busy {
            get {
                return ResourceManager.GetString("Busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Closes all the other windows ähnelt.
        /// </summary>
        public static string CloseOtherWindowsTip {
            get {
                return ResourceManager.GetString("CloseOtherWindowsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All windows will be closed. Are you sure? ähnelt.
        /// </summary>
        public static string CloseWindowsQuestion {
            get {
                return ResourceManager.GetString("CloseWindowsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Closes all open windows ähnelt.
        /// </summary>
        public static string CloseWindowsTip {
            get {
                return ResourceManager.GetString("CloseWindowsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date of the draw ähnelt.
        /// </summary>
        public static string DrawDate {
            get {
                return ResourceManager.GetString("DrawDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lottery {0} out of {1} ähnelt.
        /// </summary>
        public static string LotteryDescription {
            get {
                return ResourceManager.GetString("LotteryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die View the distribution of the numbers... ähnelt.
        /// </summary>
        public static string LotteryDistribution {
            get {
                return ResourceManager.GetString("LotteryDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Let´s calculate a lottery ticket... ähnelt.
        /// </summary>
        public static string LotteryTip {
            get {
                return ResourceManager.GetString("LotteryTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Let´s view the numbers of a lottery draw... ähnelt.
        /// </summary>
        public static string LotteryView {
            get {
                return ResourceManager.GetString("LotteryView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Opens a new window (Ctrl + N) ähnelt.
        /// </summary>
        public static string NewWindowTip {
            get {
                return ResourceManager.GetString("NewWindowTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Requery ähnelt.
        /// </summary>
        public static string Requery {
            get {
                return ResourceManager.GetString("Requery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please restart the application to change the language! ähnelt.
        /// </summary>
        public static string RestartApp {
            get {
                return ResourceManager.GetString("RestartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set as default ähnelt.
        /// </summary>
        public static string SetDefaultCountry {
            get {
                return ResourceManager.GetString("SetDefaultCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set as default ähnelt.
        /// </summary>
        public static string SetDefaultTask {
            get {
                return ResourceManager.GetString("SetDefaultTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application Log ähnelt.
        /// </summary>
        public static string TaskLog {
            get {
                return ResourceManager.GetString("TaskLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lottery Distribution ähnelt.
        /// </summary>
        public static string TaskLotteryDistribution {
            get {
                return ResourceManager.GetString("TaskLotteryDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lottery Draw ähnelt.
        /// </summary>
        public static string TaskLotteryDraw {
            get {
                return ResourceManager.GetString("TaskLotteryDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lottery Tip ähnelt.
        /// </summary>
        public static string TaskLotteryTip {
            get {
                return ResourceManager.GetString("TaskLotteryTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project Create ähnelt.
        /// </summary>
        public static string TaskProjectCreate {
            get {
                return ResourceManager.GetString("TaskProjectCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project Delete ähnelt.
        /// </summary>
        public static string TaskProjectDelete {
            get {
                return ResourceManager.GetString("TaskProjectDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project Overview ähnelt.
        /// </summary>
        public static string TaskProjectViewer {
            get {
                return ResourceManager.GetString("TaskProjectViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of rows: ähnelt.
        /// </summary>
        public static string TicketRowsNumber {
            get {
                return ResourceManager.GetString("TicketRowsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Valid until: ähnelt.
        /// </summary>
        public static string TicketValidUntil {
            get {
                return ResourceManager.GetString("TicketValidUntil", resourceCulture);
            }
        }
    }
}
