//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndritzHydro.Tuccos.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AndritzHydro.Tuccos.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TUCCOS - Turbine Calculation Service.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus:.
        /// </summary>
        public static string BonusNumber {
            get {
                return ResourceManager.GetString("BonusNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busy.
        /// </summary>
        public static string Busy {
            get {
                return ResourceManager.GetString("Busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes all the other windows.
        /// </summary>
        public static string CloseOtherWindowsTip {
            get {
                return ResourceManager.GetString("CloseOtherWindowsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All windows will be closed. Are you sure?.
        /// </summary>
        public static string CloseWindowsQuestion {
            get {
                return ResourceManager.GetString("CloseWindowsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes all open windows.
        /// </summary>
        public static string CloseWindowsTip {
            get {
                return ResourceManager.GetString("CloseWindowsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diameter Oil Pipe [mm].
        /// </summary>
        public static string DiameterOilPipe {
            get {
                return ResourceManager.GetString("DiameterOilPipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of the draw.
        /// </summary>
        public static string DrawDate {
            get {
                return ResourceManager.GetString("DrawDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner Diamter Cylinder [mm].
        /// </summary>
        public static string InnerDiamterCylinder {
            get {
                return ResourceManager.GetString("InnerDiamterCylinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length Oil Pipe [mm].
        /// </summary>
        public static string LengthOilPipe {
            get {
                return ResourceManager.GetString("LengthOilPipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loss Factor Armouring [-].
        /// </summary>
        public static string LossFactorArmouring {
            get {
                return ResourceManager.GetString("LossFactorArmouring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loss Value [-].
        /// </summary>
        public static string LossValue {
            get {
                return ResourceManager.GetString("LossValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lottery {0} out of {1}.
        /// </summary>
        public static string LotteryDescription {
            get {
                return ResourceManager.GetString("LotteryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the distribution of the numbers....
        /// </summary>
        public static string LotteryDistribution {
            get {
                return ResourceManager.GetString("LotteryDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let´s calculate a lottery ticket....
        /// </summary>
        public static string LotteryTip {
            get {
                return ResourceManager.GetString("LotteryTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let´s view the numbers of a lottery draw....
        /// </summary>
        public static string LotteryView {
            get {
                return ResourceManager.GetString("LotteryView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens a new window (Ctrl + N).
        /// </summary>
        public static string NewWindowTip {
            get {
                return ResourceManager.GetString("NewWindowTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orifice Diameter [mm].
        /// </summary>
        public static string OrificeDiameter {
            get {
                return ResourceManager.GetString("OrificeDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outer Diameter Cylinder [mm].
        /// </summary>
        public static string OuterDiameterCylinder {
            get {
                return ResourceManager.GetString("OuterDiameterCylinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial Strokes.
        /// </summary>
        public static string PartialStrokes {
            get {
                return ResourceManager.GetString("PartialStrokes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requery.
        /// </summary>
        public static string Requery {
            get {
                return ResourceManager.GetString("Requery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart the application to change the language!.
        /// </summary>
        public static string RestartApp {
            get {
                return ResourceManager.GetString("RestartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as default.
        /// </summary>
        public static string SetDefaultCountry {
            get {
                return ResourceManager.GetString("SetDefaultCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as default.
        /// </summary>
        public static string SetDefaultTask {
            get {
                return ResourceManager.GetString("SetDefaultTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Force [kN].
        /// </summary>
        public static string SingleForce {
            get {
                return ResourceManager.GetString("SingleForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Work Capacity [kW].
        /// </summary>
        public static string SingleWorkCapacity {
            get {
                return ResourceManager.GetString("SingleWorkCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Log.
        /// </summary>
        public static string TaskLog {
            get {
                return ResourceManager.GetString("TaskLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lottery Distribution.
        /// </summary>
        public static string TaskLotteryDistribution {
            get {
                return ResourceManager.GetString("TaskLotteryDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lottery Draw.
        /// </summary>
        public static string TaskLotteryDraw {
            get {
                return ResourceManager.GetString("TaskLotteryDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lottery Tip.
        /// </summary>
        public static string TaskLotteryTip {
            get {
                return ResourceManager.GetString("TaskLotteryTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Create.
        /// </summary>
        public static string TaskProjectCreate {
            get {
                return ResourceManager.GetString("TaskProjectCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Delete.
        /// </summary>
        public static string TaskProjectDelete {
            get {
                return ResourceManager.GetString("TaskProjectDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Overview.
        /// </summary>
        public static string TaskProjectViewer {
            get {
                return ResourceManager.GetString("TaskProjectViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of rows:.
        /// </summary>
        public static string TicketRowsNumber {
            get {
                return ResourceManager.GetString("TicketRowsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid until:.
        /// </summary>
        public static string TicketValidUntil {
            get {
                return ResourceManager.GetString("TicketValidUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time [s].
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Stroke [mm].
        /// </summary>
        public static string TotalStroke {
            get {
                return ResourceManager.GetString("TotalStroke", resourceCulture);
            }
        }
    }
}
