//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndritzHydro.Tuccos.localhost {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="localhost.IProject")]
    public interface IProject {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProject/GetCountries", ReplyAction="http://tempuri.org/IProject/GetCountriesResponse")]
        AndritzHydro.Tuccos.Data.Country[] GetCountries(string language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProject/GetCountries", ReplyAction="http://tempuri.org/IProject/GetCountriesResponse")]
        System.Threading.Tasks.Task<AndritzHydro.Tuccos.Data.Country[]> GetCountriesAsync(string language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProject/GetProjectList", ReplyAction="http://tempuri.org/IProject/GetProjectListResponse")]
        AndritzHydro.Tuccos.Data.Project[] GetProjectList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProject/GetProjectList", ReplyAction="http://tempuri.org/IProject/GetProjectListResponse")]
        System.Threading.Tasks.Task<AndritzHydro.Tuccos.Data.Project[]> GetProjectListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProject/SaveProject", ReplyAction="http://tempuri.org/IProject/SaveProjectResponse")]
        void SaveProject(AndritzHydro.Tuccos.Data.Project project);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProject/SaveProject", ReplyAction="http://tempuri.org/IProject/SaveProjectResponse")]
        System.Threading.Tasks.Task SaveProjectAsync(AndritzHydro.Tuccos.Data.Project project);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProjectChannel : AndritzHydro.Tuccos.localhost.IProject, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProjectClient : System.ServiceModel.ClientBase<AndritzHydro.Tuccos.localhost.IProject>, AndritzHydro.Tuccos.localhost.IProject {
        
        public ProjectClient() {
        }
        
        public ProjectClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProjectClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AndritzHydro.Tuccos.Data.Country[] GetCountries(string language) {
            return base.Channel.GetCountries(language);
        }
        
        public System.Threading.Tasks.Task<AndritzHydro.Tuccos.Data.Country[]> GetCountriesAsync(string language) {
            return base.Channel.GetCountriesAsync(language);
        }
        
        public AndritzHydro.Tuccos.Data.Project[] GetProjectList() {
            return base.Channel.GetProjectList();
        }
        
        public System.Threading.Tasks.Task<AndritzHydro.Tuccos.Data.Project[]> GetProjectListAsync() {
            return base.Channel.GetProjectListAsync();
        }
        
        public void SaveProject(AndritzHydro.Tuccos.Data.Project project) {
            base.Channel.SaveProject(project);
        }
        
        public System.Threading.Tasks.Task SaveProjectAsync(AndritzHydro.Tuccos.Data.Project project) {
            return base.Channel.SaveProjectAsync(project);
        }
    }
}
